baseurl       = "/"
contentdir    = "content"
layoutdir     = "layouts"
publishdir    = "public"
title = "UBOS - Peer Computing Platform"
canonifyurls  = true

DefaultContentLanguage = "en"
theme = [
   'hugo-theme-j12t-base'
]
metaDataFormat = "yaml"
rssLimit = 15
disableKinds = ["taxonomy", "term"]

[markup.goldmark.renderer]
    unsafe = true

[Params]
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  matomourl = "https://analytics.indiecomputing.com"
  matomositeid = 3

[Author]
  name = "Dazzle Labs Inc."

